### PR TITLE
Remove bogus module dependencies to fix #98

### LINKED ISSUE #98: `module-info.java` of `jr-stree` refers to module `com.fasterxml.jackson.jr.ob.api`, which is not defined
`module-info.java` in jr-stree requires `com.fasterxml.jackson.jr.ob.api`, but this module does not exist, this package _is_ exported by `com.fasterxml.jackson.jr.ob`, but that doesn't mean it is required to explicitly require this package.

### PR DESCRIPTION
**Pull request by cowtowncoder**
Fixes #98: invalid dependency in `module-info.java` for `jr-stree`.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@qurben does this look right? (I checked other module-info.java's as well)

**Comment by cowtowncoder** [comment]
Ok I assume this is correct, merging.

**Comment by qurben** [comment]
Yes! Thanks a lot, sorry wasn't able to verify this change earlier.

**Comment by cowtowncoder** [comment]
That's ok @qurben thank you for reporting the issue.

**Pull request merged**
